### ISSUE TITLE
Invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by joostlawerman** [authzed/spicedb#2579]
### What platforms are affected?

linux

### What architectures are affected?

amd64

### What SpiceDB version are you using?

v1.45.4

### Steps to Reproduce

Not sure, we are running spicedb in a docker container (3 instances per environment). Randomly one of the 3 instances crashes, one per +- two weeks. It is happening for some months now.

### Expected Result

No unexpected crashes/ panics, should be running stable.

### Actual Result

We get the following log, which seems to be a memory corruption of some sort.
```
Sep 24 05:54:51 panic: runtime error: invalid memory address or nil pointer dereference
Sep 24 05:54:51 [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x48b5e5]
Sep 24 05:54:51 goroutine 28 [running]:
google.golang.org/protobuf/encoding/protowire.AppendString(...)
    google.golang.org/protobuf/encoding/protowire/wire.go:479
google.golang.org/protobuf/internal/impl.appendStringValidateUTF8(...)
    google.golang.org/protobuf/internal/impl/codec_gen.go:5045 +0x91
google.golang.org/protobuf/internal/impl.(*MessageInfo).initOneofFieldCoders.func4(...)
    google.golang.org/protobuf/internal/impl/codec_field.go:96 +0x5d
google.golang.org/protobuf/internal/impl.appendMessageInfo(...)
    google.golang.org/protobuf/internal/impl/encode.go:215 +0x403
google.golang.org/protobuf/internal/impl.(*MessageInfo).marshalAppendPointer(...)
    google.golang.org/protobuf/internal/impl/codec_field.go:168 +0xa5
google.golang.org/protobuf/proto.Marshal(...)
    google.golang.org/protobuf/proto/encode.go:111 +0x50
go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp.(*client).UploadTraces(...)
    go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp/client.go:134 +0xb3
go.opentelemetry.io/otel/exporters/otlp/otlptrace.(*Exporter).ExportSpans(...)
    go.opentelemetry.io/otel/exporters/otlp/otlptrace/exporter.go:36 +0x63
go.opentelemetry.io/otel/sdk/trace.(*batchSpanProcessor).exportSpans(...)
    go.opentelemetry.io/otel/sdk/trace/batch_span_processor.go:365 +0x437
go.opentelemetry.io/otel/sdk/trace.(*batchSpanProcessor).processQueue(...)
    go.opentelemetry.io/otel/sdk/trace/batch_span_processor.go:394 +0x38c
go.opentelemetry.io/otel/sdk/trace.NewBatchSpanProcessor.func2()
    go.opentelemetry.io/otel/sdk/trace/batch_span_processor.go:145 +0x51
created by go.opentelemetry.io/otel/sdk/trace.NewBatchSpanProcessor in goroutine 1
    go.opentelemetry.io/otel/sdk/trace/batch_span_processor.go:143 +0x565
Sep 24 05:54:51 spicedb serve failed
```
Found the following issues that might be related:

- https://github.com/golang/go/issues/73024
- https://github.com/apache/skywalking/issues/13363
- https://github.com/golang/protobuf/issues/1627

**Comment by tstirrat15** [comment]
We also got a report of this on Discord:

https://cdn.discordapp.com/attachments/844600078948630559/1421065745130979339/stitched_log.png?ex=68d7ae1b&is=68d65c9b&hm=b385a3535ac534c1578d0995b919607c4ccd1b3e494bd3bf5c8a02059ffbba8d&

Things we know so far:

* This happens on both `v1.45.3` and `v1.45.4` (which included an otel library version bump)
and with both `oteltracehttp` and `oteltracegrpc`
* It's also happening on both the vtproto and non-vtproto marshalling codepaths, and both involve `AppendString`
* One codepath includes a SpiceDB proto object; the other does not appear to.

Some things that might be happening:

* There's a bug in protobuf-go where nilable input isn't being checked as such
* There's a bug in the otel library where the marshalling logic defined for one of its protos is incorrect
* There's a bug in our usage of the otel library where we're either failing to set a field that's implicitly required or passing a nil value where we shouldn't

My current guess is that it's somewhere in the otel library; that's made slightly less likely by the fact that we had a version bump between 1.45.3 and 1.45.4 and nothing changed (though the relevant code may have just been stable across those versions).

**Comment by tstirrat15** [comment]
This was also reported back in July: https://discord.com/channels/844600078504951838/1392131382108749876/1392132151633379390

That was SpiceDB v1.44.0 and we were on v1.27.0 of the otel trace library on that version.

This issue seems to be pretty deep: https://github.com/golang/protobuf/issues/1319#issuecomment-2178456496

**Comment by joostlawerman** [comment]
Somewhere in June/ July we have seen the first crashes, so yes ~ v1.44.0 seems plausible. Looked at some of the related issues, but they lack any way of consistently reproducing which is frustrating.

**Comment by miparnisari** [comment]
@joostlawerman if we had the schema and the call that was attempted prior to this panic, we could narrow this down more easily. Could you run your SpiceDB server with `--grpc-log-requests-enabled`?

**Comment by miparnisari** [comment]
@joostlawerman if you could also share your server settings/flags, that will be helpful too. 😄

**Comment by tstirrat15** [comment]
We got a report from a user that even with OTEL flags disabled, they're still experiencing crashes. They also pointed to this line in a stack trace they pulled:

https://github.com/authzed/spicedb/blob/v1.45.1/internal/services/v1/bulkcheck.go#L183

**Comment by joostlawerman** [comment]
I can add some details next week (after 27 October) currently not able to due to a holiday.

**Comment by miparnisari** [comment]
We've investigated [this](https://github.com/authzed/spicedb/issues/2579#issuecomment-3415852460) report and while we haven't found the exact root cause, we have found that one panic is triggered when doing multiple concurrent calls of BulkCheck API, when the [`with_tracing`](https://buf.build/authzed/api/docs/main:authzed.api.v1#authzed.api.v1.CheckBulkPermissionsRequest) flag is turned on.

For now, and until we find the actual root cause, we recommend _not setting this flag_, neither in BulkCheck nor Check APIs.

@joostlawerman i haven't been able to reproduce the panic log that you shared, but could you try the recommendation above and let us know if you still see the panic?

**Comment by joostlawerman** [comment]
I have seen this error latest this morning, even more frequently the last 2 weeks, consistently every 3 days on all 3 running instances. Running currently on version: 1.46.0

So we use spicedb without any direct flags. We run it in the authzed/spicedb docker container with an custom script executing `spicedb serve`.

Here are the spicedb related environment variables:
```
SPICEDB_DATASTORE_ENGINE: mysql
SPICEDB_LOG_FORMAT: json
SPICEDB_LOG_LEVEL: info
SPICEDB_OTEL_PROVIDER: otlphttp
SPICEDB_OTEL_SAMPLE_RATIO: 1.0
SPICEDB_OTEL_TRACE_PROPAGATOR: w3c
```

We use the BulkCheck API for almost all our checks. I we also have the with_tracing flag but it is always defined as `false`. I will remove the flag entirely and check if it does anything.

**Comment by josephschorr** [comment]
> I have seen this error latest this morning, even more frequently the last 2 weeks, consistently every 3 days on all 3 running instances. Running currently on version: 1.46.0

Have a stack trace, by any chance?

**Comment by joostlawerman** [comment]
@josephschorr Its the same stack trace, every time. Just as posted above.

**Comment by josephschorr** [comment]
Okay; we've seen others so I wanted to be certain

**Comment by miparnisari** [comment]
@joostlawerman are you able to share the schema that you are using?

**Comment by joostlawerman** [comment]
No I cannot, without removing all the domain specific information. So I could give a fully anonymous one, but I question how useful that could be.

**Comment by vroldanbet** [comment]
FYI `zed` offers a `backup` command that has an option to obfuscate both schema and data.

**Comment by joostlawerman** [comment]
Thanks, generated a obfuscated schema: [redacted.zed.txt](https://github.com/user-attachments/files/23209400/redacted.zed.txt)

**Comment by joostlawerman** [comment]
An update from my side, after removing the `with_tracing` flag entirely, we still see it crashing. 

Do see a correlation on how much a environment is used which I guess makes sense, might help to reproduce though. 
* In our production environment it crashes every other day, spiceDB handles ~200k requests per day.
* In our staging environment it crashes a couple of times per week, spiceDB handles ~30k requests per day.
* In our development environment it crashes twice a month at most, spiceDB handles ~1k requests per day.

**Comment by miparnisari** [comment]
I haven't been able to reproduce the exact panic that you've posted, but we merged this PR https://github.com/authzed/spicedb/pull/2629 that should be included in the next release and that i'd like for you to try out. It basically makes it so that the request de-duplicator and the response cache don't give the same object back to the callers, which is problematic if the callers attempt to modify those objects.

**Comment by joostlawerman** [comment]
Thanks, will update when it releases.

**Comment by joostlawerman** [comment]
We updated to the latest release, now running on the prod environment. Will monitor and give an update at the end of the week.

**Comment by joostlawerman** [comment]
Haven't seen a crash since the update, seems to be fixed. Thanks 😄

**Comment by tstirrat15** [comment]
That's great to hear! I'm still not entirely sure what the problem was but it helps to know that the upgrade fixed it.
